# Generated by Django 5.2.4 on 2025-08-14 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('FOOD', '음식점'), ('CAFE', '카페'), ('CONVENIENCE', '편의점'), ('OTHER', '기타')], max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('main_image_url', models.TextField(blank=True, null=True)),
                ('kakao_place_id', models.CharField(blank=True, max_length=64, null=True)),
                ('kakao_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['lat', 'lng'], name='idx_place_lat_lng'), models.Index(fields=['category'], name='places_plac_categor_0dcb38_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlaceIncidentProximity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_m', models.IntegerField()),
                ('cached_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidents.recoveryincident')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place')),
            ],
            options={
                'indexes': [models.Index(fields=['incident'], name='places_plac_inciden_3b7294_idx'), models.Index(fields=['distance_m'], name='places_plac_distanc_cf0d4f_idx')],
                'unique_together': {('place', 'incident')},
            },
        ),
    ]
