# Generated by Django 5.2.4 on 2025-08-23 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='kakao_place_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
