# Generated by Django 5.2.4 on 2025-08-19 22:28

import coupons.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='couponcode',
            name='coupons_cou_coupon__fe7362_idx',
        ),
        migrations.AlterField(
            model_name='couponcode',
            name='barcode_type',
            field=models.CharField(default='ean13', max_length=20),
        ),
        migrations.AlterField(
            model_name='couponcode',
            name='code',
            field=models.CharField(default=coupons.models.generate_coupon_code, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='couponcode',
            name='coupon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='code', to='coupons.coupon'),
        ),
        migrations.AlterField(
            model_name='couponcode',
            name='status',
            field=models.CharField(default='issued', max_length=20),
        ),
    ]
