# Generated by Django 4.2.23 on 2025-08-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RouteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('origin_lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('dest_lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('dest_lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('mode', models.CharField(max_length=10)),
                ('provider', models.CharField(max_length=10)),
                ('duration_sec', models.IntegerField()),
                ('distance_m', models.IntegerField()),
                ('raw_response', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='routes_rout_created_ffbe46_idx')],
            },
        ),
    ]
