# Generated by Django 4.2.23 on 2025-08-19 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sido', models.CharField(max_length=50)),
                ('sigungu', models.CharField(max_length=50)),
                ('dong', models.CharField(max_length=50)),
                ('center_lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('center_lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('is_safezone', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DistrictMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of_date', models.DateField()),
                ('total_grade', models.CharField(choices=[('G1', '1등급'), ('G2', '2등급'), ('G3', '3등급'), ('G4', '4등급'), ('G5', '5등급')], max_length=2)),
                ('ground_stability', models.CharField(choices=[('G1', '1등급'), ('G2', '2등급'), ('G3', '3등급'), ('G4', '4등급'), ('G5', '5등급')], max_length=2)),
                ('groundwater_impact', models.CharField(choices=[('G1', '1등급'), ('G2', '2등급'), ('G3', '3등급'), ('G4', '4등급'), ('G5', '5등급')], max_length=2)),
                ('underground_density', models.CharField(choices=[('G1', '1등급'), ('G2', '2등급'), ('G3', '3등급'), ('G4', '4등급'), ('G5', '5등급')], max_length=2)),
                ('old_building_dist', models.CharField(choices=[('G1', '1등급'), ('G2', '2등급'), ('G3', '3등급'), ('G4', '4등급'), ('G5', '5등급')], max_length=2)),
                ('analysis_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='districts.district')),
            ],
            options={
                'indexes': [models.Index(fields=['total_grade'], name='districts_d_total_g_0173e0_idx')],
                'unique_together': {('district', 'as_of_date')},
            },
        ),
    ]
