# Generated by Django 5.2.4 on 2025-08-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('districts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtmetric',
            name='incident_history',
            field=models.CharField(blank=True, choices=[('G1', '1등급'), ('G2', '2등급'), ('G3', '3등급'), ('G4', '4등급'), ('G5', '5등급')], max_length=2, null=True),
        ),
    ]
