# Generated by Django 5.2.4 on 2025-08-25 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('districts', '0002_districtmetric_incident_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigungu', models.CharField(max_length=50)),
                ('sido', models.CharField(max_length=50)),
                ('as_of_date', models.DateField()),
                ('total_grade', models.CharField(choices=[('G1', '1등급'), ('G2', '2등급'), ('G3', '3등급'), ('G4', '4등급'), ('G5', '5등급')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('sigungu', 'as_of_date')},
            },
        ),
    ]
