# Generated by Django 5.2.4 on 2025-08-25 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('districts', '0003_gumetric'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gumetric',
            index=models.Index(fields=['total_grade'], name='districts_g_total_g_b8999e_idx'),
        ),
    ]
