# Generated by Django 4.2.23 on 2025-08-19 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
                ('risk_score', models.IntegerField(blank=True, null=True)),
                ('risk_grade', models.CharField(blank=True, choices=[('G1', '1등급'), ('G2', '2등급'), ('G3', '3등급'), ('G4', '4등급'), ('G5', '5등급')], max_length=2, null=True)),
                ('advice_text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CitizenReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reports.citizenreport')),
            ],
        ),
        migrations.CreateModel(
            name='BotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=10)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='reports.citizenreport')),
            ],
        ),
    ]
