# Generated by Django 5.2.4 on 2025-08-22 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizenreport',
            name='address',
        ),
        migrations.RemoveField(
            model_name='citizenreport',
            name='advice_text',
        ),
        migrations.RemoveField(
            model_name='citizenreport',
            name='risk_grade',
        ),
        migrations.AlterField(
            model_name='citizenreport',
            name='status',
            field=models.CharField(choices=[('received', '접수됨'), ('analyzing', '분석중'), ('done', '분석완료')], default='received', max_length=20),
        ),
        migrations.AlterField(
            model_name='citizenreport',
            name='text',
            field=models.TextField(),
        ),
    ]
