# Generated by Django 5.2.4 on 2025-08-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoveryincident',
            name='cause',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recoveryincident',
            name='method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
