# Generated by Django 5.2.4 on 2025-08-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoveryincident',
            name='lat',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
        migrations.AlterField(
            model_name='recoveryincident',
            name='lng',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
    ]
