# Generated by Django 5.2.4 on 2025-08-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_alter_recoveryincident_cause_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoveryincident',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='RecoveryIncidentImage',
        ),
    ]
