# Generated by Django 5.2.4 on 2025-08-23 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('districts', '0001_initial'),
        ('incidents', '0002_alter_recoveryincident_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoveryincident',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='districts.district'),
        ),
    ]
